name: Drought Data Pipeline

# Trigger the workflow every day at midnight (cron job)
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch_and_upload_data:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository to access files
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (e.g., requests, BeautifulSoup)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Step 4: Run the Python script that fetches data
      - name: Run data download script
        run: python push-script.py

      # Step 5: Commit and push changes to the GitHub repository
      - name: Commit and push changes
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "GitHub Actions Bot"
          git add .
          git commit -m "Automated data upload"
          git push origin main
