name: Drought Data Pipeline

on:
  schedule:
    - cron: '0 0 24 9 *'

jobs:
  fetch_and_upload_data:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository to access files
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Step 4: Run your Python script
      - name: Run data download script
        run: python push-script.py

      # Step 5: Set up Git with GITHUB_TOKEN for authentication
      - name: Set up Git for pushing
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      # Step 6: Commit and push changes to GitHub
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Automated data upload"
          git push origin HEAD:main
